In [3]:
import torch

In [4]:
t1 = torch.tensor(4.)

In [5]:
t1

tensor(4.)

In [6]:
t1.dtype

torch.float32

In [7]:
t2 = torch.tensor([1.,2,3,4])

In [8]:
t2

tensor([1., 2., 3., 4.])

In [14]:
t3 = torch.tensor([[5.,6], [7,8], [9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [11]:
t4 = torch.tensor([
    [[11,12,13],
     [13,14,15]
    ]
])

In [12]:
t4

tensor([[[11, 12, 13],
         [13, 14, 15]]])

In [16]:
t1.shape

torch.Size([])

In [17]:
t2.shape

torch.Size([4])

In [18]:
t3.shape

torch.Size([3, 2])

In [19]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [31]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [32]:
# calculate derivative
y.backward()

In [33]:
print(x.grad)
print(w.grad)
print(b.grad)

None
tensor(6.)
tensor(3.)


In [34]:
 import numpy as np

In [36]:
x = np.array([[1.,2.], [3.,4.]])

In [37]:
x

array([[1., 2.],
       [3., 4.]])

In [38]:
y = torch.from_numpy(x)

In [39]:
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [40]:
x.dtype

dtype('float64')

In [41]:
y.dtype

torch.float64

In [42]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

In [43]:
# Linear regression

In [44]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [45]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [46]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [51]:
w = torch.randn(2,3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.7274,  0.0527,  1.3802],
        [ 0.7383, -0.7077,  0.8780]], requires_grad=True)
tensor([-0.7460, -0.1013], requires_grad=True)


In [72]:
def model(x):
    return x @ w.t() + b

In [73]:
preds = model(inputs)
print(preds)

tensor([[115.2366,  44.1339],
        [158.4218,  60.9999],
        [149.6571,  20.2255],
        [126.7838,  77.2609],
        [151.1225,  44.3639]], grad_fn=<AddBackward0>)


In [74]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [75]:
diff = targets - preds
diff_sqr = diff*diff
torch.sum(diff_sqr)/diff.numel()

tensor(4591.7041, grad_fn=<DivBackward0>)

In [76]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff*diff)/diff.numel()

In [77]:
loss = mse(preds, targets)

In [78]:
loss.backward()

In [79]:
print(w)
print(w.grad)

tensor([[ 0.7274,  0.0527,  1.3802],
        [ 0.7383, -0.7077,  0.8780]], requires_grad=True)
tensor([[ 5609.0444,  4803.0962,  3305.1709],
        [-3276.5796, -5159.7349, -2789.6094]])


In [80]:
print(b)
print(b.grad)

tensor([-0.7460, -0.1013], requires_grad=True)
tensor([ 64.0444, -42.6032])


In [69]:
# w.grad.zero_()
# b.grad.zero_()
# print(w.grad)
# print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [83]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [84]:
print(w)
print(b)

tensor([[ 0.5591, -0.0914,  1.2811],
        [ 0.8366, -0.5529,  0.9617]], requires_grad=True)
tensor([-0.7479, -0.1000], requires_grad=True)


In [86]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(2149.8777, grad_fn=<DivBackward0>)


In [96]:
# 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [97]:
loss

tensor(47.3709, grad_fn=<DivBackward0>)

In [98]:
preds

tensor([[ 58.1465,  72.1613],
        [ 86.8824, 103.7086],
        [106.4795, 123.0699],
        [ 27.9253,  48.0654],
        [105.9112, 117.9542]], grad_fn=<AddBackward0>)

In [99]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

## using built in methods for linear regression

In [100]:
import torch.nn as nn

In [101]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [102]:
from torch.utils.data import TensorDataset

In [103]:
train_ds = TensorDataset(inputs, targets)

In [104]:
train_ds[0:5]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [105]:
from torch.utils.data import DataLoader

In [107]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [109]:
for xb, yb in train_dl:
    print("batch: ")
    print(xb)
    print(yb)

batch: 
tensor([[ 87., 134.,  58.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[119., 133.],
        [ 56.,  70.],
        [ 22.,  37.],
        [ 22.,  37.],
        [103., 119.]])
batch: 
tensor([[ 87., 134.,  58.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.]])
tensor([[119., 133.],
        [ 81., 101.],
        [119., 133.],
        [103., 119.],
        [ 56.,  70.]])
batch: 
tensor([[ 91.,  88.,  64.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.]])
tensor([[ 81., 101.],
        [103., 119.],
        [ 22.,  37.],
        [ 81., 101.],
        [ 56.,  70.]])


In [110]:
model = nn.Linear(3, 2)

In [111]:
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3815, -0.0470, -0.2495],
        [-0.0671, -0.2876,  0.1762]], requires_grad=True)
Parameter containing:
tensor([-0.5374,  0.4749], requires_grad=True)


In [113]:
preds = model(inputs)

In [114]:
preds

tensor([[-42.2623, -16.1120],
        [-55.3548, -19.6583],
        [-54.4925, -33.6755],
        [-50.7023, -12.2119],
        [-48.8339, -19.4265],
        [-42.2623, -16.1120],
        [-55.3548, -19.6583],
        [-54.4925, -33.6755],
        [-50.7023, -12.2119],
        [-48.8339, -19.4265],
        [-42.2623, -16.1120],
        [-55.3548, -19.6583],
        [-54.4925, -33.6755],
        [-50.7023, -12.2119],
        [-48.8339, -19.4265]], grad_fn=<AddmmBackward>)

In [115]:
import torch.nn.functional as F

In [116]:
loss_fn = F.mse_loss

In [117]:
loss = loss_fn(model(inputs), targets)

In [118]:
loss

tensor(15802.5059, grad_fn=<MseLossBackward>)

In [125]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [126]:
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb, yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
            if(epoch + 1) % 10 == 0:
                print(f"epoch [{epoch+1}/{num_epochs}], loss: {loss.item()}")

In [127]:
fit(100,model, loss_fn, opt)

epoch [10/100], loss: 380.2061767578125
epoch [10/100], loss: 265.3735656738281
epoch [10/100], loss: 303.24615478515625
epoch [20/100], loss: 187.61502075195312
epoch [20/100], loss: 388.99176025390625
epoch [20/100], loss: 83.12657928466797
epoch [30/100], loss: 147.2150115966797
epoch [30/100], loss: 43.03781509399414
epoch [30/100], loss: 275.59930419921875
epoch [40/100], loss: 90.00315856933594
epoch [40/100], loss: 176.47665405273438
epoch [40/100], loss: 64.4881820678711
epoch [50/100], loss: 77.11673736572266
epoch [50/100], loss: 79.42574310302734
epoch [50/100], loss: 76.56551361083984
epoch [60/100], loss: 24.695642471313477
epoch [60/100], loss: 73.74980926513672
epoch [60/100], loss: 74.16792297363281
epoch [70/100], loss: 19.984073638916016
epoch [70/100], loss: 55.29096603393555
epoch [70/100], loss: 55.98555374145508
epoch [80/100], loss: 35.570396423339844
epoch [80/100], loss: 49.05245590209961
epoch [80/100], loss: 19.562358856201172
epoch [90/100], loss: 47.3639144

In [131]:
preds = model(inputs)
preds

tensor([[ 58.1902,  71.7359],
        [ 80.1370,  99.8615],
        [121.8725, 132.9140],
        [ 27.1828,  44.3414],
        [ 94.6451, 113.5203],
        [ 58.1902,  71.7359],
        [ 80.1370,  99.8615],
        [121.8725, 132.9140],
        [ 27.1828,  44.3414],
        [ 94.6451, 113.5203],
        [ 58.1902,  71.7359],
        [ 80.1370,  99.8615],
        [121.8725, 132.9140],
        [ 27.1828,  44.3414],
        [ 94.6451, 113.5203]], grad_fn=<AddmmBackward>)

In [132]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])